#15 Javaのエラーをパースする処理を追加した
jphacks/E_2202 pull request #84
Opened 2022-11-06 14:43 UTC by Hamumayo55

## やったこと
* 検索クエリの作成
* 下記の画像のように検索クエリ部分を赤色、コード内でエラーの原因と思われる部分を黄色で表示させた
<img width="1218" alt="スクリーンショット 2022-11-06 22 48 20" src="https://user-images.githubusercontent.com/33239413/200177114-af088687-f2b5-47f8-b20c-ac4d5bcde195.png">

## できるようになること（ユーザ目線）

* Javaのエラーも使えるようになった

## できなくなること（ユーザ目線）

* あるわけがない

## その他

* フロントのリクエストでjavaの項目がないため、動作確認をするときはmain.pyの53行目を
`result =java.error_parser(error_contents.error_text)`に変更させてください。

close #\d

2022-11-07 12:38 UTC, kagari requested changes
ちょっと気になった所あるので対応お願いします！

2022-11-07 12:38 UTC, kagari commented on server/main.py
> +        return ImportantErrorLines(result=result)
`elif` 後は `else:` で other につなげるのもありかなと思うのですが，どうでしょう？

2022-11-07 12:38 UTC, kagari commented on server/parser/java.py
> +error_occurs_pattern = re.compile(r"\(\w+.java:\d\)")
`:` が必須になっているけど， `:` が無いエラーが抽出されなくなっている...
例：https://github.com/jphacks/E_2202/pull/84#issuecomment-1305529505

2022-11-07 12:38 UTC, kagari commented on server/parser/java.py
> +error_occurs_pattern = re.compile(r"\(\w+.java:\d\)")
あ，ここじゃなくて `exception_name_pattern` かもしれない

2022-11-08 13:08 UTC, kagari approved these changes

2022-11-08 13:08 UTC, kagari commented on server/main.py
>      # TODO: 今後対応する言語が増えたらmatchに変更する方がいいかも
TODO消してね♡

2022-11-09 12:25 UTC, soto0201 approved these changes
よさそう
LGTM!!!!!!!!!!!!!!!

2022-11-09 12:26 UTC, merged